// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXmPOpcYeeD3tucWW3dE1e-bPQnkpPkYc',
    appId: '1:769966559735:web:261afa29afdd93d51f1ef2',
    messagingSenderId: '769966559735',
    projectId: 'agriconnect-50b10',
    authDomain: 'agriconnect-50b10.firebaseapp.com',
    storageBucket: 'agriconnect-50b10.appspot.com', // fixed
    measurementId: 'G-JM9E71GV5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQaRuveD4ai6jAqpAoSe8cu__JA1fs-_g',
    appId: '1:769966559735:android:0cd2478f938c0a451f1ef2',
    messagingSenderId: '769966559735',
    projectId: 'agriconnect-50b10',
    storageBucket: 'agriconnect-50b10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_RhDKlinOL1QIvTOQaijPs1ElGzySGgA',
    appId: '1:769966559735:ios:2a0feb3ce14f362e1f1ef2',
    messagingSenderId: '769966559735',
    projectId: 'agriconnect-50b10',
    storageBucket: 'agriconnect-50b10.appspot.com',
    iosBundleId: 'com.example.agriconnect',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXmPOpcYeeD3tucWW3dE1e-bPQnkpPkYc',
    appId: '1:769966559735:web:dde05047c23169351f1ef2',
    messagingSenderId: '769966559735',
    projectId: 'agriconnect-50b10',
    authDomain: 'agriconnect-50b10.firebaseapp.com',
    storageBucket: 'agriconnect-50b10.appspot.com', // fixed
    measurementId: 'G-B8RSBBQ57K',
  );
}
